HelloSSIFI/HelloWorld

programmers/Lv2_문자열_압축/s1_kcw0360.py, programmers/Lv2_문자열_압축/s2_kcw0360.py, programmers/Lv2_오픈채팅방/s1_kcw0360.py, programmers/Lv3_추석_트래픽/s1_kcw0360.py
=> 05.31 프로그래머스

BAEKJOON/1062_가르침/s1_lbefull.py, BAEKJOON/14719_빗물/s1_lbefull.py, BAEKJOON/14888_연산자_끼워넣기/s1_lbefull.py, BAEKJOON/2504_괄호의값/s1_lbefull.py
- 14888_연산자_끼워넣기
- 2504_괄호의값
- 14719_빗물
- 1062_가르침
=> [lbefull] 백준 0531 ~ 0603

BAEKJOON/1062_가르침/s1_KSoonYo.py, BAEKJOON/14719_빗물/s1_KSoonYo.py, BAEKJOON/14888_연산자_끼워넣기/s1_KSoonYo.py, BAEKJOON/2504_괄호의값/s1_KSoonYo.py
14888_연산자 끼워넣기
1062_가르침
2504_괄호의값
14719_빗물
=> KSoonYo BAEKJOON 0604 study 문제 풀이

BAEKJOON/1062_가르침/s1_kcw0360.py, BAEKJOON/14719_빗물/s1_kcw0360.py, BAEKJOON/14888_연산자_끼워넣기/s1_kcw0360.py, BAEKJOON/2504_괄호의값/s1_kcw0360.py
- 1062 가르침
- 2504 괄호의 값
- 14719 빗물
- 14888 연산자 끼워넣기
=> 22.06.04 BAEKJOON

programmers/Lv2_124나라의숫자/s1_lbefull.py, programmers/Lv2_기능개발/s1_lbefull.py, programmers/Lv2_멀쩡한_사각형/s1_lbefull.py, programmers/Lv2_멀쩡한_사각형/s2_lbefull.py
- Lv2_124나라의숫자
- Lv2_기능개발
- Lv2_멀쩡한_사각형
=> [lbefull] 프로그래머스 0604 ~ 0606

programmers/Lv2_124나라의숫자/s1_kcw0360.py, programmers/Lv2_기능개발/s1_kcw0360.py, programmers/Lv2_멀쩡한_사각형/s1_kcw0360.py
- 멀쩡한 사각형
- 124 나라의 숫자
- 기능 개발
=> sovled programmers 22.06.07

BAEKJOON/1197_최소_스패닝_트리/s1_lbefull.py, BAEKJOON/1197_최소_스패닝_트리/s2_lbefull.py, BAEKJOON/1700_멀티탭_스케줄링/s1_lbefull.py, BAEKJOON/1806_부분합/s1_lbefull.py, BAEKJOON/1916_최소비용_구하기/s1_lbefull.py
- 1700_멀티탭_스케줄링
- 1806_부분합
- 1916_최소비용_구하기
- 1197_최소_스패닝_트리
=> [lbefull] 백준 0607 ~ 0610

BAEKJOON/1197_최소_스패닝_트리/s1_kcw0360.py, BAEKJOON/1700_멀티탭_스케줄링/s1_kcw0360.py, BAEKJOON/1806_부분합/s1_kcw0360.py, BAEKJOON/1916_최소비용_구하기/s1_kcw0360.py
- 멀티탭 스케줄링
- 최소 비용 구하기
- 부분합
- 최소 스패닝 트리
=> solved BAEKJOON 22.06.11

BAEKJOON/1197_최소_스패닝_트리/s1_KSoonYo.py, BAEKJOON/1197_최소_스패닝_트리/s2_KSoonYo.py, BAEKJOON/1806_부분합/s1_KSoonYo.py, BAEKJOON/1806_부분합/s2_KSoonYo.py, BAEKJOON/1806_부분합/s3_KSoonYo.py, BAEKJOON/1916_최소비용_구하기/s1_KSoonYo.py, programmers/Lv2_124나라의숫자/s1_KSoonYo.py
1806_부분합
1916_최소비용 구하기
1197_최소 스패닝 트리
1700_멀티탭 스케줄링(미완료)
=> KSoonYo BAEKJOON 0607, 0608, 0609, 0610 problems

programmers/Lv2_더_맵게/s1_lbefull.py, programmers/Lv2_타켓_넘버/s1_lbefull.py, programmers/Lv3_N으로_표현/s1_lbefull.py
- Lv2_더_맵게
- Lv3_N으로_표현
- Lv2_타겟_넘버
=> [lbefull] 프로그래머스 0611 ~ 0613

programmers/Lv2_더_맵게/s1_kcw0360.py, programmers/Lv2_타켓_넘버/s1_kcw0360.py, programmers/Lv3_N으로_표현/s1_kcw0360.py
- Lv2 더 맵게
- Lv2 타겟 넘버
- Lv3 N으로 표현
=> 22.06.14 programmers

BAEKJOON/1916_최소비용_구하기/s1_KSoonYo.py, programmers/Lv2_더_맵게/s1_KSoonYo.py, programmers/Lv2_타켓_넘버/s1_KSoonYo.py, programmers/Lv3_N으로_표현/s1_KSoonYo.py
programmers 
Lv2 더 맵게
Lv3 N으로 표현
Lv2 타겟 넘버
=> KSoonYo programmers 0611 ~ 0614

BAEKJOON/16916_부문_문자열/s1_KSoonYo.py, BAEKJOON/1789_수들의_합/s1_KSoonYo.py, BAEKJOON/2252_줄_세우기/s1_KSoonYo.py, BAEKJOON/2252_줄_세우기/s2_KSoonYo.py, BAEKJOON/2293_동전_1/s1_KSoonYo.py, BAEKJOON/2293_동전_1/s2_KSoonYo.py, programmers/Lv2_더_맵게/s1_KSoonYo.py
2293_동전1 
16916_부분 문자열(fail)
2252_줄_세우기
1789_수들의 합
=> KSoonYo BAEKJOON 0614 ~ 0617

BAEKJOON/16916_부문_문자열/s1_kcw0360.py, BAEKJOON/1789_수들의_합/s1_kcw0360.py, BAEKJOON/2252_줄_세우기/s1_kcw0360.py, BAEKJOON/2293_동전_1/s1_kcw0360.py
- 1789 수들의 합
- 2252 줄 세우기
- 2293 동전 1
- 16916 부분 문자열
=> 22.06.13 BAEKJOON

programmers/Lv2_짝지어_제거하기/s1_lbefull.py, programmers/Lv3_가장_먼_노드/s1_lbefull.py, programmers/Lv3_입국심사/s1_lbefull.py
- Lv3_입국심사
- Lv3_가장_먼_노드
- Lv2_짝지어_제거하기
=> [lbefull] 프로그래머스 0618 ~ 0620

programmers/Lv2_짝지어_제거하기/s1_kcw0360.py, programmers/Lv3_가장_먼_노드/s1_kcw0360.py, programmers/Lv3_입국심사/s1_kcw0360.py
- Lv3 입국심사
- Lv3 가장 먼 노드
- Lv2 짝지어 제거하기
=> 22.06.21 programmers

BAEKJOON/1038_감소하는_수/s1_lbefull.py, BAEKJOON/2294_동전_2/s1_lbefull.py, BAEKJOON/2667_단지번호붙이기/s1_lbefull.py, BAEKJOON/3085_사탕_게임/s1_lbefull.py
- 3085_사탕_게임
- 2294_동전_2
- 2667_단지번호붙이기
- 1038_감소하는_수
=> [lbefull] 백준 0621 ~ 0624

BAEKJOON/1038_감소하는_수/s1_kcw0360.py, BAEKJOON/2294_동전_2/s1_kcw0360.py, BAEKJOON/2667_단지번호붙이기/s1_kcw0360.py, BAEKJOON/3085_사탕_게임/s1_kcw0360.py
- 2294 동전2
- 2667 단지번호 붙이기
- 1038 감소하는 수
- 3085 사탕 게임
=> solved BAEKJOON 22.06.25

BAEKJOON/1038_감소하는_수/s1_KSoonYo.py, BAEKJOON/1700_멀티탭_스케줄링/s1_KSoonYo.py, BAEKJOON/2294_동전_2/s1_KSoonYo.py, BAEKJOON/2667_단지번호붙이기/s1_KSoonYo.py, BAEKJOON/3085_사탕_게임/s1_KSoonYo.py, programmers/Lv3_가장_먼_노드/defaultdict_KSoonYo.py
1038_감소하는_수
2294_동전_2
2667_단지번호붙이기
3085_사탕_게임
1700_멀티탭_스케줄링 solve
=> KSoonYo BAEKJOON 0621 ~ 0624

programmers/Lv2_k진수에서_소수_개수_구하기/s1_KSoonYo.py, programmers/Lv2_메뉴_리뉴얼/s1_KSoonYo.py, programmers/Lv2_주차_요금_계산/s1_KSoonYo.py, programmers/Lv2_행렬_테두리_회전하기/s1_KSoonYo.py
Lv2_주차_요금_계산
Lv2_k진수에서_소수_개수_구하기
Lv2_양궁대회(fail)
Lv3_양과늑대(fail)
Lv2_행렬_테두리_회전하기
Lv2_메뉴_리뉴얼(미완료)
Lv2_괄호_변환(미완료)
=> KSoonYo programmers 0625 ~ 0628

BAEKJOON/1260_DFS와_BFS/s1_lbefull.py, BAEKJOON/12851_숨바꼭질_2/s1_lbefull.py, BAEKJOON/15486_퇴사_2/s1_lbefull.py, BAEKJOON/17070_파이프_옮기기_1/s1_lbefull.py
- 17070_파이프_옮기기_1
- 1260_DFS와_BFS
- 12851_숨바꼭질_2
- 15486_퇴사_2
=> [lbefull] 백준 0628 ~ 0701

BAEKJOON/1260_DFS와_BFS/s1_kcw0360.py, BAEKJOON/12851_숨바꼭질_2/s1_kcw0360.py, BAEKJOON/15486_퇴사_2/s1_kcw0360.py, BAEKJOON/17070_파이프_옮기기_1/s1_kcw0360.py
- 1260 DFS와 BFS
- 12851 숨바꼭질 2
- 15486 퇴사 2
- 17070 파이프 옮기기 1
=> add BAEKJOON

BAEKJOON/1062_가르침/s1_KSoonYo.py, BAEKJOON/15486_퇴사_2/s1_KSoonYo.py, BAEKJOON/16916_부문_문자열/s1_KSoonYo.py
BAEKJOON 1062_가르침 solve
BAEKJOON 16916_부문_문자열 sovle(KMP 알고리즘)
BAEKJOON 15486_퇴사_2 solve
=> KSoonYo 이전 미완료 문제 풀이 + 백준 한 문제

programmers/Lv2_1차_뉴스_클러스터링/s1_lbefull.py, programmers/Lv2_거리두기_확인하기/s1_lbefull.py, programmers/Lv2_수식_최대화/s1_lbefull.py
- Lv2_1차_뉴스_클러스터링
- Lv2_거리두기_확인하기
- Lv2_수식_최대화
=> [lbefull] 프로그래머스 0702 ~ 0704

BAEKJOON/1303_전쟁_전투/s1_lbefull.py, BAEKJOON/13549_숨바꼭질_3/s1_lbefull.py, BAEKJOON/15989_1_2_3_더하기_4/s1_lbefull.py, BAEKJOON/15989_1_2_3_더하기_4/s2_lbefull.py, BAEKJOON/1890_점프/s1_lbefull.py
- 1303_전쟁_전투
- 13549_숨바꼭질_3
- 1890_점프
- 15989_1_2_3_더하기_4
=> [lbefull] 백준 0705 ~ 0708

programmers/Lv2_1차_캐시/s1_lbefull.py, programmers/Lv2_1차_프렌즈4블록/s1_lbefull.py, programmers/Lv2_3차_방금그곡/s1_lbefull.py, programmers/Lv2_빛의_경로_사이클/s1_lbefull.py, programmers/Lv2_전화번호_목록/s1_lbefull.py, programmers/Lv2_튜플/s1_lbefull.py, programmers/Lv3_1차_셔틀버스/s1_lbefull.py
- Lv2_튜플
- Lv2_1차_프렌즈4블록
- Lv2_1차_캐시
- Lv2_3차_방금그곡
- Lv3_1차_셔틀버스
- Lv2_빛의_경로_사이클
- Lv2_전화번호_목록
=> 프로그래머스 0709 ~ 0711

programmers/Lv2_1차_캐시/s1_kcw0360.py, programmers/Lv2_1차_프렌즈4블록/s1_kcw0360.py, programmers/Lv2_3차_방금그곡/s1_kcw0360.py, programmers/Lv2_빛의_경로_사이클/s1_kcw0360.py, programmers/Lv2_전화번호_목록/s1_kcw0360.py, programmers/Lv2_튜플/s1_kcw0360.py, programmers/Lv3_1차_셔틀버스/s1_kcw0360.py
test
- Lv2 캐시
- Lv2 프렌즈 4블록
- Lv2 방금그곡
- Lv3 셔틀버스
- Lv2 튜플
- Lv2 빛의 경로 사이클
- Lv2 전화번호 목록
=> programmers 22.07.12

BAEKJOON/11058_크리보드/s1_lbefull.py, BAEKJOON/1495_기타리스트/s1_lbefull.py, BAEKJOON/1743_음식물_피하기/s1_lbefull.py, BAEKJOON/2178_미로_탐색/s1_lbefull.py
- 2178_미로_탐색
- 1743_음식물_피하기
- 1495_기타리스트
- 11058_크리보드
=> [lbefull] 백준 0712 ~ 0715

programmers/Lv2_가장_큰_수/s1_lbefull.py, programmers/Lv2_프린터/s1_lbefull.py, programmers/Lv3_디스크_컨트롤러/s1_lbefull.py
- Lv2_프린터
- Lv3_디스크_컨트롤러
- Lv2_가장_큰_수
=> 프로그래머스 0716 ~ 0718

BAEKJOON/16197_두_동전/s1_lbefull.py, BAEKJOON/1949_우수_마을/s1_lbefull.py, BAEKJOON/2176_합리적인_이동경로/s1_lbefull.py, BAEKJOON/2533_사회망_서비스_SNS/s1_lbefull.py
- 16197_두_동전
- 2176_합리적인_이동경로
- 2533_사회망_서비스_SNS
- 1949_우수_마을
=> [lbefull] 백준 0719 ~ 0722

BAEKJOON/16197_두_동전/s1_kcw0360.py, BAEKJOON/1949_우수_마을/s1_kcw0360.py, BAEKJOON/2176_합리적인_이동경로/s1_kcw0360.py, BAEKJOON/2533_사회망_서비스_SNS/s1_kcw0360.py
- 우수마을
- 합리적인 이동경로
- 두 동전
- 사회망 서비스 SNS
=> solved BAEKJOON 22.07.23

programmers/Lv2_소수_찾기/s1_kcw0360.py, programmers/Lv2_조이스틱/s1_kcw0360.py, programmers/Lv3_정수_삼각형/s1_kcw0360.py
- Lv2 소수 찾기
- Lv2 조이스틱
- Lv3 정수 삼각형
=> sovled programmers problem 22.07.26

programmers/Lv2_소수_찾기/s1_lbefull.py, programmers/Lv2_조이스틱/s1_lbefull.py, programmers/Lv3_정수_삼각형/s1_lbefull.py
- Lv2_소수_찾기
- Lv2_조이스틱
- Lv3_정수_삼각형
=> [lbefull] 프로그래머스 0723 ~ 0725

programmers/Lv2_소수_찾기/s1_KSoonYo.py, programmers/Lv2_조이스틱/s1_KSoonYo.py
Lv2_조이스틱 fail
Lv2_소수찾기 solve
Lv3_정수_삼각(미제출)
=> KSoonYo programmers 0723 - 0725

BAEKJOON/1005_ACM_Craft/s1_kcw0360.py, BAEKJOON/2023_신기한_소수/s1_kcw0360.py, BAEKJOON/2281_데스노트/s1_kcw0360.py, BAEKJOON/9470_Strahler_순서/s1_kcw0360.py
- 2281 데스노트
- 1005 ACM Craft
- 2023 신기한 소수
- 9470 Strahler 순서
=> sovled BAEKJOON 22.07.30

BAEKJOON/1005_ACM_Craft/s1_lbefull.py, BAEKJOON/2023_신기한_소수/s1_lbefull.py, BAEKJOON/2281_데스노트/s1_lbefull.py, BAEKJOON/9470_Strahler_순서/s1_lbefull.py
- 2023_신기한_소수
- 2281_데스노트
- 9470_Strahler_순서
- 1005_ACM_Craft
=> [lbefull] 백준 0726 ~ 0729

programmers/2022_코딩테스트_실전_대비_모의고사/s1_lbefull.py, programmers/2022_코딩테스트_실전_대비_모의고사/s2_lbefull.py, programmers/2022_코딩테스트_실전_대비_모의고사/s3_lbefull.py, programmers/2022_코딩테스트_실전_대비_모의고사/s4_lbefull.py, programmers/Lv2_게임_맵_최단거리/s1_lbefull.py, programmers/Lv3_네트워크/s1_lbefull.py, programmers/Lv3_순위/s1_lbefull.py
- Lv2_게임_맵_최단거리
- Lv3_네트워크
- Lv3_순위
- 2022 모의고사
=> [lbefull] 프로그래머스 0730 ~ 0801 + 모의고사

programmers/2022_코딩테스트_실전_대비_모의고사/s1_kcw0360.py, programmers/2022_코딩테스트_실전_대비_모의고사/s2_kcw0360.py, programmers/2022_코딩테스트_실전_대비_모의고사/s3_kcw0360.py, programmers/2022_코딩테스트_실전_대비_모의고사/s4_kcw0360.py, programmers/Lv2_게임_맵_최단거리/s1_kcw0360.py, programmers/Lv3_네트워크/s1_kcw0360.py, programmers/Lv3_순위/s1_kcw0360.py
- Lv2 게임 맵 최단거리
- Lv3 순위
- Lv3 네트워크
=> solved programmers 22.08.02

BAEKJOON/11049_행렬_곱셈_순서/s1_kcw0360.py, BAEKJOON/11559_Puyo_Puyo/s1_kcw0360.py, BAEKJOON/14226_이모티콘/s1_kcw0360.py, BAEKJOON/2616_소형기관차/s1_kcw0360.py, programmers/2022_코딩테스트_실전_대비_모의고사/s4_kcw0360.py, programmers/Lv2_순위_검색/s1_kcw0360.py, programmers/Lv2_예상_대진표/s1_kcw0360.py, programmers/Lv3_다단계_칫솔_판매/s1_kcw0360.py, programmers/Lv3_다단계_칫솔_판매/s2_kcw0360.py
- 11049 행렬 곱셈 순서
- 14226 이모티콘
- 11559 puyo puyo
- 2616 소형 기관차
- Lv2 예상 대진표
- Lv2 순위 검색
- Lv2 다단계 칫솔 판매
=> soveld BAEKJOON &programmers 

BAEKJOON/11049_행렬_곱셈_순서/s1_lbefull.py, BAEKJOON/11559_Puyo_Puyo/s1_lbefull.py, BAEKJOON/14226_이모티콘/s1_lbefull.py, BAEKJOON/2616_소형기관차/s1_lbefull.py, programmers/Lv2_순위_검색/s1_lbefull.py, programmers/Lv2_예상_대진표/s1_lbefull.py, programmers/Lv3_다단계_칫솔_판매/s1_lbefull.py
- 14226_이모티콘
- 2616_소형기관차
- 11559_Puyo_Puyo
- 11049_행렬_곱셈_순서
- Lv2_예상_대진표
- Lv3_다단계_칫솔_판매
- Lv2_순위_검색
=> [lbefull] 백준 0802 ~ 0805 + 프로그래머스 0806 ~ 0808

BAEKJOON/1141_접두사/s1_kcw0360.py, BAEKJOON/12100_2048_easy/s1_kcw0360.py, BAEKJOON/7579_앱/s1_kcw0360.py, BAEKJOON/9935_문자열_폭발/s1_kcw0360.py
- 1141 접두사
- 7579 앱
- 9935 문자열 폭발
- 12100 2048(easy)
=> solved BAEKJOON 22.08.13

BAEKJOON/1141_접두사/s1_lbefull.py, BAEKJOON/12100_2048_easy/s1_lbefull.py, BAEKJOON/7579_앱/s1_lbefull.py, BAEKJOON/9935_문자열_폭발/s1_lbefull.py
- 1141_접두사
- 9935_문자열_폭발
- 12100_2048_easy
- 7579_앱
=> [lbefull] 백준 0809 ~ 0812

programmers/Lv2_후보키/s1_lbefull.py, programmers/Lv3_자물쇠와_열쇠/s1_lbefull.py, programmers/Lv3_표_편집/s1_lbefull.py
- Lv3_자물쇠와_열쇠
- Lv2_후보키
- Lv3_표_편집
=> [lbefull] 프로그래머스 0813 ~ 0815

BAEKJOON/14226_이모티콘/s1_kcw0360.py, programmers/Lv2_후보키/s1_kcw0360.py, programmers/Lv3_자물쇠와_열쇠/s1_kcw0360.py, programmers/Lv3_표_편집/s1_kcw0360.py
- Lv2 후보키
- Lv3 자물쇠와 열쇠
- Lv3 표 편집
=> solved programmers 22.08.16

BAEKJOON/12100_2048_easy/s1_KSoonYo.py, programmers/Lv2_후보키/s1_KSoonYo.py, programmers/Lv3_표_편집/s1_KSoonYo.py
Lv2 후보키 solve
Lv3 표 편집 solve
Lv3_자물쇠와_열쇠 fail
=> KSoonYo 0816 study problems

BAEKJOON/12026_BOJ_거리/s1_lbefull.py, BAEKJOON/12869_뮤탈리스크/s1_lbefull.py, BAEKJOON/16930_달리기/s1_lbefull.py, BAEKJOON/17086_아기_상어_2/s1_lbefull.py
- 12026_BOJ_거리
- 17086_아기_상어_2
- 16930_달리기
- 12869_뮤탈리스크
=> [lbefull] 백준 0816 ~ 0819

BAEKJOON/12869_뮤탈리스크/s1_KSoonYo.py, BAEKJOON/17086_아기_상어_2/s1_KSoonYo.py, programmers/Lv3_자물쇠와_열쇠/s1_KSoonYo.py
programmers Lv3 자물쇠와 열쇠 solved
baekjoon 아기상어 2 solve
baekjoon 뮤탈리스크 solve
=> KSoonYo problems solved

programmers/Lv3_금과_은_운반하기/s1_kcw0360.py, programmers/Lv3_보석_쇼핑/s1_kcw0360.py, programmers/Lv3_불량_사용자/s1_kcw0360.py
- Lv3 보석 쇼핑
- Lv3 불량 사용자
- Lv3 금과 은 운반하기
=> solved programmers 22.08.23

BAEKJOON/10942_팰린드롬/s1_lbefull.py, BAEKJOON/11066_파일_합치기/s1_lbefull.py, BAEKJOON/6987_월드컵/s1_lbefull.py, BAEKJOON/8911_거북이/s1_lbefull.py
- 8911_거북이
- 10942_팰린드롬
- 11066_파일_합치기
- 6987_월드컵
=> [lbefull] 백준 0823 ~ 0826

BAEKJOON/10942_팰린드롬/s1_kcw0360.py, BAEKJOON/11066_파일_합치기/s1_kcw0360.py, BAEKJOON/6987_월드컵/s1_kcw0360.py, BAEKJOON/8911_거북이/s1_kcw0360.py
- 8911 거북이
- 6987 월드컵
- 10942 팰린드롬
- 11066 파일 합치기
=> sovled baekjoon 22.08.27

BAEKJOON/17143_낚시왕/s1_lbefull.py, BAEKJOON/17144_미세먼지_안녕/s1_lbefull.py, programmers/Lv2_2_x_n_타일링/s1_lbefull.py, programmers/Lv2_괄호_회전하기/s1_lbefull.py, programmers/Lv2_배달/s1_lbefull.py
- Lv2_괄호_회전하기
- Lv2_배달
- Lv2_2_x_n_타일링
- 17144_미세먼지_안녕
- 17143_낚시왕
=> [lbefull] 프로그래머스 0827 ~ 0829 + 0827 테스트

programmers/Lv2_다리를_지나는_트럭/s1_lbefull.py, programmers/Lv2_두_큐_합_같게_만들기/s1_lbefull.py, programmers/Lv2_위장/s1_lbefull.py, programmers/Lv3_등산코스_정하기/s1_lbefull.py, programmers/Lv3_이중우선순위큐/s1_lbefull.py, programmers/Lv3_이중우선순위큐/s2_lbefull.py, programmers/Lv3_코딩_테스트_공부/s1_lbefull.py
- Lv2_위장
- Lv2_다리를_지나는_트럭
- Lv3_이중우선순위큐
- Lv2_두_큐_합_같게_만들기
- Lv3_코딩_테스트_공부
- Lv3_등산코스_정하기
=> [lbefull] 프로그래머스 0903 ~ 0905 + 0905 테스트

programmers/Lv2_다리를_지나는_트럭/s1_kcw0360.py, programmers/Lv2_두_큐_합_같게_만들기/s1_kcw0360.py, programmers/Lv2_위장/s1_kcw0360.py, programmers/Lv3_등산코스_정하기/s1_kcw0360.py, programmers/Lv3_이중우선순위큐/s1_kcw0360.py, programmers/Lv3_코딩_테스트_공부/s1_kcw0360.py
- Lv2 두 큐 합 같게 만들기
- Lv3 등산 코스 정하기 
- Lv3 코딩 테스트 공부
- Lv2 위장
- Lv2 다리를 지나는 트럭
- Lv3 이중 우선 순위 큐
=> solved test & programmers 22.09.06

programmers/Lv2_H_Index/s1_kcw0360.py, programmers/Lv2_카펫/s1_kcw0360.py, programmers/Lv2_큰_수_만들기/s1_kcw0360.py
- Lv2 카펫
- Lv2 H-Index
- Lv2 큰 수 만들기
=> solved programmers 22.0913

programmers/Lv2_H_Index/s1_lbefull.py, programmers/Lv2_카펫/s1_lbefull.py, programmers/Lv2_큰_수_만들기/s1_lbefull.py
- Lv2_H_Index
- Lv2_카펫
- Lv2_큰_수_만들기
=> [lbefull] 프로그래머스 0913

BAEKJOON/1194_달이_차오른다_가자/s1_kcw0360.py, BAEKJOON/14425_문자열_집합/s1_kcw0360.py, BAEKJOON/17779_게리맨더링_2/s1_kcw0360.py, BAEKJOON/17837_새로운_게임_2/s1_kcw0360.py, BAEKJOON/2933_미네랄/s1_kcw0360.py, BAEKJOON/9251_LCS/s1_kcw0360.py, programmers/Lv2_피로도/s1_kcw0360.py, programmers/Lv3_공_이동_시뮬레이션/s1_kcw0360.py, programmers/Lv3_아이템_줍기/s1_kcw0360.py
BAEJOON
- 14425 문자열 집합
- 9251 LCS
- 2933 미네랄
- 1194 달이 차오른다, 가자
TEST
- 17779 게리맨더링 2
- 17837 새로운 게임 2
programmers
- Lv2 피로도
- Lv3 아이템 줍기
- Lv3 공 이동 시뮬레이션
=> solved problems 22.09.20

BAEKJOON/11000_강의실_배정/s1_lbefull.py, BAEKJOON/1174_줄어드는_수/s1_lbefull.py, BAEKJOON/15898_피아의_아틀리에_신비한_대회의_연금술사/s1_lbefull.java, BAEKJOON/2470_두_용액/s1_lbefull.py, programmers/Lv2_n^2_배열_자르기/s1_lbefull.py, programmers/Lv2_교점에_별_만들기/s1_lbefull.py, programmers/Lv2_전력망을_둘로_나누기/s1_lbefull.py
- 11000_강의실_배정
- 1174_줄어드는_수
- 15898_피아의_아틀리에_신비한_대회의_연금술사
- 2470_두_용액
- Lv2_n^2_배열_자르기
- Lv2_전력망을_둘로_나누기
- Lv2_교점에_별_만들기
=> [lbefull] 0927 백준 + 프로그래머스 문제풀이

BAEKJOON/11000_강의실_배정/s1_kcw0360.py, BAEKJOON/1174_줄어드는_수/s1_kcw0360.py, BAEKJOON/2470_두_용액/s1_kcw0360.py, programmers/Lv2_n^2_배열_자르기/s1_kcw0360.py, programmers/Lv2_교점에_별_만들기/s1_kcw0360.py, programmers/Lv2_전력망을_둘로_나누기/s1_kcw0360.py
- 2470 두 용액
- 1174 줄어드는 수
- 11000 강의실 배정
- Lv2 배열 자르기
- Lv2 전력망 둘로 나누기
- Lv2 교점에 별 만들기
=> solved problems 22.09.27

BAEKJOON/16234_인구_이동/s1_lbefull.py, BAEKJOON/17140_이차원_배열의_연산/s1_lbefull.py, BAEKJOON/17142_연구소_3/s1_lbefull.py, BAEKJOON/20437_문자열_게임_2/s1_lbefull.py, BAEKJOON/20444_색종이와_가위/s1_lbefull.py, BAEKJOON/5373_큐빙/s1_lbefull.py, programmers/Lv2_모음사전/s1_lbefull.py, programmers/Lv3_사라지는_발판/s1_lbefull.py, programmers/Lv3_파괴되지_않은_건물/s1_lbefull.py
- 20437_문자열_게임_2
- 16234_인구_이동
- 5373_큐빙
- 20444_색종이와_가위
- Lv2_모음사전
- Lv3_파괴되지_않은_건물
- Lv3_사라지는_발판
- 17140_이차원_배열과_연산
- 17142_연구소_3
=> [lbefull] 1004 백준 + 프로그래머스 문제풀이

BAEKJOON/16234_인구_이동/s1_kcw0360.py, BAEKJOON/17140_이차원_배열의_연산/s1_kcw0360.py, BAEKJOON/17142_연구소_3/s1_kcw0360.py, BAEKJOON/20437_문자열_게임_2/s1_kcw0360.py, BAEKJOON/20444_색종이와_가위/s1_kcw0360.py, BAEKJOON/5373_큐빙/s1_kcw0360.py, programmers/Lv2_모음사전/s1_kcw0360.py, programmers/Lv3_사라지는_발판/s1_kcw0360.py, programmers/Lv3_파괴되지_않은_건물/s1_kcw0360.py
- 16234 인구 이동
- 20444 색종이와 가위
- 20437 문자열 게임2
- 5373 큐빙
- 17142 연구소 3
- 17140 이차원 배열과 연산
- Lv2 모음사전
- Lv3  파괴되지 않은 건물
- Lv3 사라지는 발판
=> solved problems 22.10.04

BAEKJOON/1106_호텔/s1_tlsqktem483.py, BAEKJOON/16235_나무_재테크/s1_tlsqktem483.py, BAEKJOON/16236_아기_상어/s1_tlsqktem483.py, BAEKJOON/22942_데이터_체커/s1_tlsqktem483.py, BAEKJOON/22942_데이터_체커/s2_tlsqktem483.py, programmers/Lv2_2개_이하로_다른_비트/s1_tlsqktem483.py, programmers/Lv3_110_옮기기/s1_tlsqktem483.py, programmers/Lv3_퍼즐_조각_채우기/s1_tlsqktem483.py
BAEKJOON
- 1106
- 16235
- 16236
- 22942
Programmers
- Lv2_2개이하로다른비트
- Lv3_110옮기기
- Lv3_퍼즐조각채우기
=> 1011 Algo study by tlsqktem483

BAEKJOON/1106_호텔/s1_lbefull.py, BAEKJOON/16235_나무_재테크/s1_lbefull.py, BAEKJOON/16236_아기_상어/s1_lbefull.py, BAEKJOON/17822_원판_돌리기/s1_lbefull.py, BAEKJOON/17825_주사위_윷놀이/s1_lbefull.py, BAEKJOON/22942_데이터_체커/s1_lbefull.py, programmers/Lv2_2개_이하로_다른_비트/s1_lbefull.py, programmers/Lv3_110_옮기기/s1_lbefull.py, programmers/Lv3_퍼즐_조각_채우기/s1_lbefull.py
- 1106_호텔
- 22942_데이터_체커
- 16235_나무_재테크
- 16236_아기_상어
- Lv2_2개_이하로_다른_비트
- Lv3_퍼즐_조각_채우기
- Lv3_110_옮기기
- 17822_원판_돌리기
- 17825_주사위_윷놀이
=> [lbefull] 1011 백준 + 프로그래머스 문제풀이

BAEKJOON/1106_호텔/s1_kcw0360.py, BAEKJOON/16235_나무_재테크/s1_kcw0360.py, BAEKJOON/16236_아기_상어/s1_kcw0360.py, BAEKJOON/17822_원판_돌리기/s1_kcw0360.py, BAEKJOON/17825_주사위_윷놀이/s1_kcw0360.py, BAEKJOON/22942_데이터_체커/s1_kcw0360.py, programmers/Lv2_2개_이하로_다른_비트/s1_kcw0360.py, programmers/Lv3_110_옮기기/s1_kcw0360.py, programmers/Lv3_퍼즐_조각_채우기/s1_kcw0360.py
baekjoon
- 1106 호텔
- 22942 데이터 체커
- 16236 아기 상어
- 16235 나무 재테크
test
- 17822 원판 돌리기
- 17825 주사위 윷놀이
programmers
- Lv2 2개 이하로 다른 비트
- Lv3 110 옮기기
- Lv3 퍼즐 조각 채우기
=> solved problems 22.10.11

BAEKJOON/1068_트리/s1_lbefull.py, BAEKJOON/11265_끝나지_않는_파티/s1_lbefull.py, BAEKJOON/11265_끝나지_않는_파티/s2_lbefull.py, BAEKJOON/19236_청소년_상어/s1_lbefull.py, BAEKJOON/19237_어른_상어/s1_lbefull.py, BAEKJOON/20057_마법사_상어와_토네이도/s1_lbefull.py, BAEKJOON/20058_마법사_상어와_파이어스톰/s1_lbefull.py, programmers/Lv2_할인_행사/s1_lbefull.py, programmers/Lv2_혼자_놀기의_달인/s1_lbefull.py, programmers/Lv3_카운트_다운/s1_lbefull.py, programmers/Lv3_카운트_다운/s2_lbefull.py
- 1068_트리
- 11265_끝나지_않는_파티
- 20057_마법사_상어와_토네이도
- 20058_마법사_상어와_파이어스톰
- Lv2_혼자_놀기의_달인
- Lv3_카운트_다운
- Lv2_할인_행사
- 19236_청소년_상어
- 19237_어른_상어
=> [lbefull] 1018 백준 + 프로그래머스 문제풀이

BAEKJOON/1477_휴게소_세우기/s1_kcw0360.py, BAEKJOON/2015_수들의_합_4/s1_kcw0360.py, BAEKJOON/2141_우체국/s1_kcw0360.py, BAEKJOON/2624_동전_바꿔주기/s1_kcw0360.py, programmers/Lv2_이진_변환_반복하기/s1_kcw0360.py, programmers/Lv3_광고_삽입/s1_kcw0360.py, programmers/Lv3_모두_0으로_만들기/s1_kcw0360.py, programmers/Lv3_스타_수열/s1_kcw0360.py, programmers/Lv3_카드_짝_맞추기/s1_kcw0360.py, programmers/Lv3_합승_택시_요금/s1_kcw0360.py
- 1477 휴게소 세우기
- 2015 수들의 합 4
- 2141 우체국
- 2624 동전 바꿔주기
- Lv3 합승 택시 요금
- Lv3 광고 삽입
- Lv3  카드 짝 맞추기
- Lv2 이진 변환 반복하기
- Lv3 모두 0으로 만들기
- Lv3 스타 수열
=> sovled problems 22.10.25

BAEKJOON/1477_휴게소_세우기/s1_lbefull.py, BAEKJOON/2015_수들의_합_4/s1_lbefull.py, BAEKJOON/2141_우체국/s1_lbefull.py, BAEKJOON/2624_동전_바꿔주기/s1_lbefull.py, programmers/Lv2_이진_변환_반복하기/s1_lbefull.py, programmers/Lv3_광고_삽입/s1_lbefull.py, programmers/Lv3_모두_0으로_만들기/s1_lbefull.py, programmers/Lv3_스타_수열/s1_lbefull.py, programmers/Lv3_카드_짝_맞추기/s1_lbefull.py, programmers/Lv3_합승_택시_요금/s1_lbefull.py
- 1477_휴게소_세우기
- 2015_수들의_합_4
- 2141_우체국
- 2624_동전_바꿔주기
- Lv2_이진_변환_반복하기
- Lv3_모두_0으로_만들기
- Lv3_스타_수열
- Lv3_광고_삽입
- Lv3_카드_짝_맞추기
- Lv3_합승_택시_요금
=> [lbefull] 1025 백준 + 프로그래머스 문제풀이

BAEKJOON/15927_회문은_회문아니야/s1_kcw0360.py, BAEKJOON/1600_말이_되고픈_원숭이/s1_kcw0360.py, BAEKJOON/17485_진우의_달_여행/s1_kcw0360.py, BAEKJOON/2115_갤러리/s1_kcw0360.py, BAEKJOON/21922_학부_연구생_민상/s1_kcw0360.py, BAEKJOON/2493_탑/s1_kcw0360.py, BAEKJOON/7569_토마토/s1_kcw0360.py, programmers/Lv2_롤케이크_자르기/s1_kcw0360.py, programmers/Lv2_택배상자/s1_kcw0360.py, programmers/Lv3_부대복귀/s1_kcw0360.py
- 1600 말이 되고픈 원숭이
- 2493 탑
- 15927 회문은 회문아니야!!
- 17485 진우의 달 여행
- 7569 토마토
- 21922 학부 연구생 민상
- 2115 갤러리
- Lv2 롤케이크 자르기
- Lv2 택배상자
- Lv3 부대복귀
=> solved problems 22.11.01

BAEKJOON/1660_캡틴_이다솜/s1_lbefull.py, BAEKJOON/18430_무기_공학/s1_lbefull.py, BAEKJOON/2302_극장_좌석/s1_lbefull.py, BAEKJOON/7511_소셜_네트워킹_어플리케이션/s1_lbefull.py, programmers/Lv2_연속_부분_수열_합의_개수/s1_lbefull.py, programmers/Lv3_2차원_동전_뒤집기/s1_lbefull.py, programmers/Lv3_고고학_최고의_발견/s1_lbefull.py
- 1660_캡틴_이다솜
- 18430_무기_공학
- 2302_극장_좌석
- 7511_소셜_네트워킹_어플리케이션
- Lv2_연속_부분_수열_합의_개수
- Lv3_2차원_동전_뒤집기
- Lv3_고고학_최고의_발견
=> [lbefull] 1119 백준 + 프로그래머스 문제풀이

BAEKJOON/19535_ㄷㄷㄷㅈ/s1_lbefull.py, BAEKJOON/23288_주사위_굴리기_2/s1_lbefull.py, BAEKJOON/2623_음악프로그램/s1_lbefull.py, BAEKJOON/2688_줄어들지_않아/s1_lbefull.py, programmers/Lv2_삼각_달팽이/s1_lbefull.py, programmers/Lv2_쿼드압축_후_개수_세기/s1_lbefull.py, programmers/Lv3_풍선_터트리기/s1_lbefull.py
- Lv2_쿼드압축_후_개수_세기
- Lv3_풍선_터트리기
- Lv2_삼각_달팽이
- 2623_음악프로그램
- 2688_줄어들지_않아
- 19535_ㄷㄷㄷㅈ
- 23288_주사위_굴리기_2
=> [lbefull] 1129 백준 + 프로그래머스 문제풀이

programmers/Lv2_귤_고르기/s1_kcw0360.py, programmers/Lv2_숫자_카드_나누기/s1_kcw0360.py, programmers/Lv2_우박수열_정적분/s1_kcw0360.py
- Lv2 귤 고르기
- Lv2 숫자 카드 나누기
- Lv2 우박 수열 정적분
=> 22.12.06 solved problems

programmers/Lv3_기둥과_보_설치/s1_kcw0360.py, programmers/Lv3_블록_이동하기/s1_kcw0360.py, programmers/Lv3_외벽_점검/s1_kcw0360.py
- Lv3 기둥과 보 설치
- Lv3 블록 이동하기
- Lv3 외벽 점검
=> 22.12.20 solved problems

programmers/Lv2_방문_길이/s1_lbefull.py, programmers/Lv2_스킬트리/s1_lbefull.py, programmers/Lv3_기둥과_보_설치/s1_lbefull.py, programmers/Lv3_블록_이동하기/s1_lbefull.py, programmers/Lv3_외벽_점검/s1_lbefull.py
- Lv3_블록_이동하기
- Lv3_외벽_점검
- Lv3_기둥과_보_설치
- Lv2_방문_길이
- Lv2_스킬트리
=> [lbefull] 1224 문제풀이

programmers/Lv2_방문_길이/s1_kcw0360.py, programmers/Lv2_스킬트리/s1_kcw0360.py
=> 22.12.24 solved problems

programmers/Lv2_n진수_게임/s1_kcw0360.py, programmers/Lv2_압축/s1_kcw0360.py, programmers/Lv2_파일명_정렬/s1_kcw0360.py
- Lv2 n진수 게임
- Lv2 압축
- Lv2 파일명 정렬
=> 22.12.31 solved problems

programmers/Lv2_n진수_게임/s1_lbefull.py, programmers/Lv2_압축/s1_lbefull.py, programmers/Lv2_파일명_정렬/s1_lbefull.py
- Lv2_n진수_게임
- Lv2_압축
- Lv2_파일명_정렬
=> [lbefull] 1231 문제풀이

programmers/Lv2_마법의_엘리베이터/s1_kcw0360.py, programmers/Lv2_유사_칸토어_비트열/s1_kcw0360.py, programmers/Lv3_경주로_건설/s1_kcw0360.py, programmers/Lv3_징검다리_건너기/s1_kcw0360.py
- Lv2 마법의 엘리베이터
- Lv2 유사 칸토어 비트열
- Lv3 경주로 건설
- Lv3 징검다리 건너기
=> 22.01.07 solved problems

programmers/Lv2_마법의_엘리베이터/s1_lbefull.py, programmers/Lv2_유사_칸토어_비트열/s1_lbefull.py, programmers/Lv3_경주로_건설/s1_lbefull.py, programmers/Lv3_징검다리_건너기/s1_lbefull.py
- Lv3_경주로_건설
- Lv3_징검다리_건너기
- Lv2_마법의_엘리베이터
- Lv2_유사_칸토어_비트열
=> [lbefull] 0107 문제풀이

programmers/Lv2_이모티콘_할인행사/s1_lbefull.py, programmers/Lv2_택배_배달과_수거하기/s1_lbefull.py, programmers/Lv3_표_병합/s1_lbefull.py, programmers/Lv3_표현_가능한_이진트리/s1_lbefull.py
- Lv2_이모티콘_할인행사
- Lv2_택배_배달과_수거하기
- Lv3_표현_가능한_이진트리
- Lv3_표_병합
=> [lbefull] 0211 문제풀이

programmers/Lv2_뒤에_있는_큰_수_찾기/s1_lbefull.py, programmers/Lv2_무인도_여행/s1_lbefull.py, programmers/Lv2_숫자_변환하기/s1_lbefull.py, programmers/Lv2_시소_짝꿍/s1_lbefull.py, programmers/Lv2_점_찍기/s1_lbefull.py, programmers/Lv2_호텔_대실/s1_lbefull.py, programmers/Lv2_호텔_대실/s2_lbefull.py
- Lv2_호텔_대실
- Lv2_무인도_여행
- Lv2_뒤에_있는_큰_수_찾기
- Lv2_숫자_변환하기
- Lv2_시소_짝꿍
- Lv2_점_찍기
=> [lbefull] 0225 문제풀이

programmers/Lv3_단속카메라/s1_lbefull.py, programmers/Lv3_단어_변환/s1_lbefull.py, programmers/Lv3_동굣길/s1_lbefull.py, programmers/Lv3_섬_연결하기/s1_lbefull.py, programmers/Lv3_여행경로/s1_lbefull.py
- Lv3_여행경로
- Lv3_단어_변환
- Lv3_동굣길
- Lv3_단속카메라
- Lv3_섬_연결하기
=> [lbefull] 0311 문제풀이

BAEKJOON/21608_상어_초등학교/s1_lbefull.py, BAEKJOON/21609_상어_중학교/s1_lbefull.py
- 21608_상어_초등학교
- 21609_상어_중학교
=> [lbefull] 0325 문제풀이

BAEKJOON/21608_상어_초등학교/s1_kcw0360.py, BAEKJOON/21609_상어_중학교/s1_kcw0360.py, programmers/Lv2_광물_캐기/s1_kcw0360.py, programmers/Lv3_고고학_최고의_발견/s1_kcw0360.py, programmers/Lv3_인사고과/s1_kcw0360.py, programmers/Lv3_풍선_터트리기/s1_kcw0360.py
- 21608 상어 초등학교
- 21609 상어 중학교
이전 못푼 문제
- Lv3 풍선 터트리기
- Lv3 고고학 최고의 발견
개별적으로 푼 문제
- Lv3 인사고과
- Lv2 광물 캐기
=> 23.03.25 solved problems
